name: Extension
on:
  workflow_call:
    outputs:
      artifact-url:
        description: "The URL of the uploaded extension artifact"
        value: ${{ jobs.extension.outputs.artifact-url }}

jobs:
  extension:
    name: Extension
    runs-on: ubuntu-latest
    outputs:
      artifact-url: ${{ steps.artifact-upload-step.outputs.artifact-url }}
    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          submodules: 'recursive'

      - name: Set up pnpm
        uses: wevm/actions/.github/actions/pnpm@main

      - name: Set extension version
        run: |
          cd src
          PORTO_VERSION=$(pnpm pkg get version | sed 's/"//g')
          cd ../apps/extension
          pnpm pkg set version=$PORTO_VERSION

      - name: Zip extension
        run: |
          pnpm --filter extension zip
          pnpm --filter extension zip:firefox

      - name: Upload artifacts
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: ./apps/extension/.output/*.zip
          include-hidden-files: true
