name: Extension
on:
  workflow_call:
    outputs:
      artifact-url:
        description: "The URL of the uploaded extension artifact"
        value: ${{ jobs.extension.outputs.artifact-url }}

jobs:
  extension:
    name: Extension
    runs-on: ubuntu-latest
    outputs:
      artifact-url: ${{ steps.artifact-upload-step.outputs.artifact-url }}
    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          submodules: 'recursive'

      - name: Set up pnpm
        uses: wevm/actions/.github/actions/pnpm@f7ad7f00e16e73322562922c241f21f0c7ffbbec # main

      - name: Set extension version
        run: |
          cd src
          PORTO_VERSION=$(pnpm pkg get version | sed 's/"//g')
          cd ../apps/extension
          pnpm pkg set version=$PORTO_VERSION

      - name: Set preview env vars
        if: github.ref_name != 'main'
        run: |
          BRANCH=$(echo "${{ github.head_ref }}" | sed 's/[_/]/-/g' | tr '[:upper:]' '[:lower:]')
          echo "VITE_DIALOG_HOST=https://dialogporto-git-${BRANCH}.preview.porto.sh/dialog/" >> $GITHUB_ENV

      - name: Zip extension
        run: |
          pnpm --filter extension zip
          pnpm --filter extension zip:firefox

      - name: Upload artifacts
        id: artifact-upload-step
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: extension
          path: ./apps/extension/.output/*.zip
          include-hidden-files: true
